/**
 * Class OipfError that represents an error.
 * @summary
 * This is based on the standard javascript Error but contains 4 extra properties:
 * <pre>
 * type:       This is an id for the error. In an application the type of a a top level error is of the
 *             form AA9 to AA9999.
 *             All other error types should be a number less than 10,000.
 *
 * printable:  This is a user displayable code for the error, used for customers to report to call centres.
 *             This is auto formed and cannot be set explicitly.
 *
 *             It is generated as :
 *                 type / additionalCode  - type is of form AA9999 & additionalCode is non empty string
 *                 type                   - type is of form AA9999
 *                 / type /additionalCode - type is numeric < 1000 & additionalCode is non empty string
 *                 / type                 - type is numeric < 1000
 *                 / additionalCode       - additionalCode is non empty string
 *                 empty string           - otherwise
 *             If additionalCode starts with / a prefix / is not added
 *              eg. type    additionalCode   result
 *                  SP12    14               SP12/14
 *                  7                        /7
 *                  7       SEA25            /7/SEA25
 *                  SP01    /15/SEA12        SP01/15/SEA12
 *                  SAR3    6                empty string
 *             The SDK returns errors which have a printable of the form /number/code, these can be
 *             added directly to an app error message or incorporated into a OipfError the app generates as
 *             an additionalCode. So each time the .printable can be passed into the next level up error
 *             constructor as the additionalCode value.
 *
 * additionalCode:   The user displayable error (printable) can be built up from codes from sub errors
 *                   (eg. server responses) and this is codes from sub errors.
 *
 * category:         Indicates the error is shown to the user (displayed), will be followed by a retry
 *                   (retry) or neither of these (hidden). Defaults to displayed.
 *
 * Standard use of Error is to create a constructor function for each new error.
 * With this class each new error is just an id string and you use this class to create your error.
 *
 * This OipfError class can be used to return errors via exceptions, callback functions, and events.
 * Once an OipfError has been created it is only permissible to change the category and the message.
 *
 * Use directly for an error that has no payload extra to a message and inherit to derive your own class
 * where a payload is required.
 *
 * Note: must use new (unlike Error which will work without).
 * </pre>
 *
 * @example
 * new OipfError("ER12", "A valid url must be supplied"); // generated by an app
 * new OipfError("8", "No such Id", "SEA12/OTE1234"); // generated by a library due to a server error
 * new OipfError("8", "No such Id", "SEA12/OTE1234", "hidden"); // error occurs in the background and is not shown to the user
 */
class OipfError extends Error {
    /**
     * Constructor, creates a base error given its contents. The printable value will be auto generated, see class summary section.
     * @param	{Number|String} type short id that represents the type of the error
     * @param	{String} message detailed error message
     * @param	{String} additionalCode any additional error codes which may be raised by external services - see class summary
     * @param	{String} [category = displayed] can be either 'hidden', 'retry' or 'displayed' - see class summary for further info
     */
    constructor(type, message, additionalCode, category) {
        super(message); //call superclass constructor

        this.type = type;
        this.category = category || 'displayed';
        this.additionalCode = additionalCode;

        this.printable = '';
        if (typeof type === 'number' && !isNaN(type) && type < 10000) {
            this.printable += '/' + String(type);
        } else if (typeof type === 'string' && /^[A-Z][A-Z]\d{1,4}$/.exec(type)) {
            //This regex matches two capital letters, followed by one to four numbers only
            this.printable = type;
        }

        if (additionalCode !== null && additionalCode !== undefined && additionalCode !== '') {
            additionalCode = String(additionalCode);
            this.printable += (additionalCode.charAt(0) === '/' ? '' : '/') + additionalCode;
        }
    }
}

export default OipfError;
